### PR TITLE
Added workdays and holidays for 2024 year

### PR DESCRIPTION
**Pull request by wrmk**
http://duma.gov.ru/news/57708/

### CODE REVIEW

**Review by greenfork — APPROVED** [review]
We also need to publish a new version of the gem. @sergey-tomashevsky-toughbyte if I remember correctly, you did this previously, could you provide instructions for @wrmk to do it himself?

**Comment by wrmk** [comment]
@greenfork may I merge and update gem in Hub?

**Comment by greenfork** [comment]
Sure, if you know how to do it

**Comment by wrmk** [comment]
ah, I see. we pull this gem from rubygems

**Comment by sergey-tomashevsky** [comment]
@wrmk Since #13 CI should automatically publish new game version to rubygems.org. After that you simply have to pull new gem version in Hub and create new PR there with updated gem version.

**Comment by greenfork** [comment]
Okay, merging. @wrmk please make sure that the gem gets published, after that we can update it during our monthly update cycle

**Comment by greenfork** [comment]
Gem was successfully pushed

**Pull request merged**
